from plugins import genParent

def gen(cb):
	plugin_ids=["%/etc/security/user - mindiff%"]
	plugin_ids+=["%/etc/security/user - minage%"]
	plugin_ids+=["%/etc/security/user - maxage%"]
	plugin_ids+=["%/etc/security/user - minlen%"]
	plugin_ids+=["%/etc/security/user - minalpha%"]
	plugin_ids+=["%/etc/security/user - minother%"]
	plugin_ids+=["%/etc/security/user - maxrepeats%"]
	plugin_ids+=["%/etc/security/user - histexpire%"]
	plugin_ids+=["%/etc/security/user - histsize%"]
	plugin_ids+=["%/etc/security/user - maxexpired%"]
	plugin_ids+=["%/etc/security/user - minloweralpha%"]
	plugin_ids+=["%/etc/security/user - minupperalpha%"]
	plugin_ids+=["%/etc/security/user - mindigit%"]
	plugin_ids+=["%/etc/security/user - minspecialchar%"]
	plugin_ids+=["%/etc/security/user - loginretries%"]
	plugin_ids+=["%/etc/security/user - rlogin%"]
	plugin_ids+=["%/etc/security/user - sugroups%"]
	plugin_ids+=["%/etc/inetd.conf - telnet%"]
	plugin_ids+=["%/etc/inetd.conf - FTP%"]
	plugin_ids+=["%crontab permissions%"]
	plugin_ids+=["%Configuring SSH - disabling direct root access%"]
	plugin_ids+=["%Configuring SSH - server protocol 2%","%Configuring SSH - server protocol - Protocol 2%"]
	plugin_ids+=["%Configuring SSH - ignore .shosts and .rhosts%"]
	plugin_ids+=["%Configuring SSH - disable null passwords%"]
	plugin_ids+=["%Configuring SSH - set LogLevel to INFO%"]
	plugin_ids+=["%Configuring SSH - set MaxAuthTries to 4 or Less%"]
	plugin_ids+=["%Configuring SSH - set Idle Timeout Interval for User Login - ClientAliveCountMax%","%Configuring SSH - set Idle Timeout Interval for User Login - ClientAliveInterval%"]
	plugin_ids+=["%Configuring SSH - restrict Cipher list%"]
	plugin_ids+=["%Configuring SSH - ignore user-provided environment variables%"]
	plugin_ids+=["%Configuring SSH - sshd_config permissions lockdown%"]
	plugin_ids+=["%/etc/mail/sendmail.cf - SmtpGreetingMessage%"]
	plugin_ids+=["%/etc/mail/sendmail.cf - permissions and ownership%"]
	plugin_ids+=["%/var/spool/mqueue - permissions and ownership%"]
	plugin_ids+=["%NFS - nosuid on NFS client mounts%"]
	#	plugin_ids+=["%Permissions and Ownership - /smit.log%"]
	plugin_ids+=["%Permissions and Ownership - /var/adm/cron/log%","%Permissions and Ownership - /var/adm/cron/log root:cron 660"]
	plugin_ids+=["%Permissions and Ownership - /var/spool/cron/crontabs - files%","%Permissions and Ownership - /var/spool/cron/crontabs/ root:cron 770"]
	plugin_ids+=["%Permissions and Ownership - /var/adm/cron/at.allow%","%Permissions and Ownership - /var/adm/cron/at.allow root:sys 400"]
	plugin_ids+=["%Permissions and Ownership - /var/adm/cron/cron.allow%","%Permissions and Ownership - /var/adm/cron/cron.allow root:sys 400%"]
	plugin_ids+=["%Permissions and Ownership - /var/adm/ras%","%Permissions and Ownership - /var/adm/ras/* files are not world readable or writable"]
	plugin_ids+=["%Permissions and Ownership - /var/ct/RMstart.log%","%Permissions and Ownership - /var/ct/RMstart.log root:system 640"]
	#	plugin_ids+=["%Permissions and Ownership - /var/tmp/dpid2.log%"]
	plugin_ids+=["%Permissions and Ownership - /var/adm/sa%","%Permissions and Ownership - /var/adm/sa adm:adm 755"]
	plugin_ids+=["%Permissions and Ownership - home directory configuration files%"]
	plugin_ids+=["%Permissions and Ownership - home directory permissions - existing home directories%"]
	plugin_ids+=["%Permissions and Ownership - home directory permissions - new home directories%"]
	plugin_ids+=["%Permissions and Ownership - world/group writable directory in root PATH%"]
	plugin_ids+=["%Miscellaneous Config - authorized users in at.allow - adm%","%Miscellaneous Config - authorized users in at.allow - sys%","%Miscellaneous Config - authorized users in at.allow - at.allow contains adm","%Miscellaneous Config - authorized users in at.allow - at.allow contains sys"]
	plugin_ids+=["%Miscellaneous Config - authorized users in cron.allow - adm%","%Miscellaneous Config - authorized users in cron.allow - sys%","%Miscellaneous Config - authorized users in cron.allow - cron.allow contains adm","%Miscellaneous Config - authorized users in cron.allow - cron.allow contains sys","%Miscellaneous Config - authorized users in cron.allow - cron.allow contains no other entries besides sys and adm"]
	plugin_ids+=["%Miscellaneous Config - all unlocked accounts must have a password%","%Miscellaneous Config - all unlocked accounts must have a password%"]
	plugin_ids+=["%Miscellaneous Config - unnecessary user and group removal - /etc/group - printq%","%Miscellaneous Config - unnecessary user and group removal - /etc/group - uucp%","%Miscellaneous Config - unnecessary user and group removal - /etc/passwd - lpd%","%Miscellaneous Config - unnecessary user and group removal - /etc/passwd - nuucp%","%Miscellaneous Config - unnecessary user and group removal - /etc/passwd - uucp%"]
	plugin_ids+=["%Miscellaneous Config - ftp umask%"]

	description="Build Review\nThe following finding details the observations made during a system build review carried out against one or more AIX 7.1 hosts.\nThe assessed host(s) were each seen to be running a deployment of AIX 7.1. Their present configuration was compared against the recommended settings for AIX deployments laid out within the CIS benchmarks and the following observations were made.\n\n<url>https://benchmarks.cisecurity.org/tools2/aix/CIS_IBM_AIX_7.1_Benchmark_v1.1.0.pdf</url>"

	genParent.genr(cb, plugin_ids, description)
