from plugins import genParent

def gen(cb):
	plugin_ids=['Flash Player %', 'Adobe Flash Player %']
	plugin_ids+=['Shockwave Player %', 'Adobe Shockwave Player %']
	plugin_ids+=['Adobe Reader %', 'Adobe Acrobat %']
	plugin_ids+=['Firefox %','Mozilla Foundation Unsupported Application Detection', 'Mozilla Firefox %']
	plugin_ids+=['Adobe AIR %']
	plugin_ids+=['Oracle Java %', 'Sun Java %']
	plugin_ids+=['Citrix ICA Client%', 'Citrix XenApp Online Plug-in %','Citrix Receiver / Online Plug-in Remote Code Execution (CTX134681)']	
	plugin_ids+=['Google Chrome %']	
	plugin_ids+=['Wireshark %']	
	plugin_ids+=['VLC %']	
	plugin_ids+=['VMware vSphere Client %']
	plugin_ids+=['Cisco VPN Client cvpnd.exe Privilege Escalation','Cisco VPN Client Unsupported']	
	plugin_ids+=['Microsoft Silverlight Unsupported Version Detection (Windows)']	
	plugin_ids+=['HP Version Control Agent (VCA) < %']	
	plugin_ids+=['HP Version Control Repository Manager%']	
	plugin_ids+=['FileZilla Client %']	
	plugin_ids+=['Microsoft Internet Explorer Unsupported Version Detection']
	plugin_ids+=['Microsoft Office Service Pack Out of Date','Microsoft Office Unsupported Version Detection']	
	plugin_ids+=['Microsoft .NET Framework Unsupported','Microsoft .NET Framework Service Pack Out of Date']	
	plugin_ids+=['Microsoft SQL Server Unsupported Version Detection']
	plugin_ids+=['Microsoft Visio Unsupported Version Detection']	
	plugin_ids+=['Adobe Digital Editions%']	
	plugin_ids+=['WinZIP Unsupported']	
	plugin_ids+=['7-Zip Unsupported','7-Zip < 16%']	
	plugin_ids+=['WinSCP %']	
	plugin_ids+=['PuTTY %']	
	plugin_ids+=['IBM Notes %','Lotus Notes %','IBM Lotus Notes %']	
	plugin_ids+=['IBM DB2 9.7 %']	
	plugin_ids+=['IBM Tivoli Storage Manager Client %','IBM Spectrum Protect Client%']
	plugin_ids+=['IBM Domino %']	
	plugin_ids+=['HP Systems Insight Manager < %']	
	plugin_ids+=['OpenVPN %']	
	plugin_ids+=['Firebird SQL Server %']	
	plugin_ids+=['VMware vCenter / vRealize Orchestrator %']	
	plugin_ids+=['Google SketchUp %']	
	plugin_ids+=['Adobe Photoshop %','Photoshop %']	
	plugin_ids+=['Adobe Flash Professional%']	
	plugin_ids+=['Adobe Illustrator %']	
	plugin_ids+=['Apple Quicktime %','Quicktime %']	
	plugin_ids+=['VMware Player %']
	plugin_ids+=['Adobe Camera Raw %']
	plugin_ids+=['Apple Software Update Insecure Transport']	
	plugin_ids+=['LibreOffice < %']	
	plugin_ids+=['Apache OpenOffice <%']	
	plugin_ids+=['Apple iTunes < %']	
	plugin_ids+=['Autodesk AutoCAD%']	
	plugin_ids+=['Autodesk Design Review <%']	
	plugin_ids+=['Cygwin <%']	
	plugin_ids+=['VMware Horizon View Client%(VMSA-%','VMware Horizon View Client <%']
	description="Outdated Client Software\nSeveral instances of outdated client software have been found on systems across the network. Client software does not generally present services to the network and therefore does not pose a direct threat to the hosting system; however, if a user can be made to access malicious files or URLs, an attacker can potentially exploit issues within the software to execute code with the privilege level of the user running the software."

	genParent.genr(cb, plugin_ids, description)
