#!/bin/bash
sed -i 's/\\A/\\\\A/g' buildReviewWindows.py
sed -i 's/\\B/\\\\B/g' buildReviewWindows.py
sed -i 's/\\C/\\\\C/g' buildReviewWindows.py
sed -i 's/\\D/\\\\D/g' buildReviewWindows.py
sed -i 's/\\E/\\\\E/g' buildReviewWindows.py
sed -i 's/\\F/\\\\F/g' buildReviewWindows.py
sed -i 's/\\G/\\\\G/g' buildReviewWindows.py
sed -i 's/\\H/\\\\H/g' buildReviewWindows.py
sed -i 's/\\I/\\\\I/g' buildReviewWindows.py
sed -i 's/\\J/\\\\J/g' buildReviewWindows.py
sed -i 's/\\K/\\\\K/g' buildReviewWindows.py
sed -i 's/\\L/\\\\L/g' buildReviewWindows.py
sed -i 's/\\M/\\\\M/g' buildReviewWindows.py
sed -i 's/\\N/\\\\N/g' buildReviewWindows.py
sed -i 's/\\O/\\\\O/g' buildReviewWindows.py
sed -i 's/\\P/\\\\P/g' buildReviewWindows.py
sed -i 's/\\Q/\\\\Q/g' buildReviewWindows.py
sed -i 's/\\R/\\\\R/g' buildReviewWindows.py
sed -i 's/\\S/\\\\S/g' buildReviewWindows.py
sed -i 's/\\T/\\\\T/g' buildReviewWindows.py
sed -i 's/\\U/\\\\U/g' buildReviewWindows.py
sed -i 's/\\V/\\\\V/g' buildReviewWindows.py
sed -i 's/\\W/\\\\W/g' buildReviewWindows.py
sed -i 's/\\X/\\\\X/g' buildReviewWindows.py
sed -i 's/\\Y/\\\\Y/g' buildReviewWindows.py
sed -i 's/\\Z/\\\\Z/g' buildReviewWindows.py

